/*
    Title: Contest_SECTION action types
    Description: Contest_SECTION action types
    Author: Iqbal Hossain
    Date: 24-August-2022
    Modified: 24-August-2022
*/

export const FETCH_CONTEST_SECTION = 'FETCH_CONTEST_SECTION';
export const FETCH_CONTEST_SECTION_BY_QUERY = 'FETCH_CONTEST_SECTION_BY_QUERY';
export const ADD_CONTEST_SECTION = 'ADD_CONTEST_SECTION';
export const FETCH_CONTEST_SECTION_BY_ID = 'FETCH_CONTEST_SECTION_BY_ID';
export const FETCH_CONTEST_SECTION_DETAILS_BY_ID = 'FETCH_CONTEST_SECTION_DETAILS_BY_ID';
export const UPDATE_CONTEST_SECTION = 'UPDATE_CONTEST_SECTION';
export const DELETE_CONTEST_SECTION = 'DELETE_CONTEST_SECTION';
export const TOGGLE_CONTEST_SECTION_MODAL = 'TOGGLE_CONTEST_SECTION_MODAL';
export const LOADING = 'LOADING';
